<div class="container" style="margin-top:10px;">
    <div class="jumbotron">
        <h1>ASSIGNMENT</h1>
    </div>
    <h3><span class="label label-info">Q.</span> 3, 5, 9, 15, X, Y, Z - Please create a new function for
        finding X, Y, Z value</h3>
    <h3><span class="label label-success">A.</span> <?php echo $this->ans1; ?></h3>
    <h3><span class="label label-info">Q.</span> Please use “Place search|Place API(by Google)” for finding all restaurants in Bangsue area and show result by JSON</h3>
    <h3><span class="label label-success">A.</span> <?php print_r( $this->ans2['results'] ) ; ?></h3>
</div>